<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="GZ-QA-AutoTool" name="KWS.prepare.t15_03_14_07_45_11" tests="3" failures="0" timestamp="14 Mar 2015 14:48:01 GMT" time="161.293" errors="1">
  <testcase name="TestBaidu" time="17.005" classname="KWS.prepare.t15_03_14_07_45_11"/>
  <testcase name="couplesearch" time="40.202" classname="KWS.prepare.t15_03_14_07_45_11">
    <error type="java.lang.AssertionError" message="TIME OUT!! 20 second(s) has passed,but did not find element [By.xpath: //a[text()=&#039;Registry&#039;]] ">
      <![CDATA[java.lang.AssertionError: TIME OUT!! 20 second(s) has passed,but did not find element [By.xpath: //a[text()='Registry']] 
	at org.testng.Assert.fail(Assert.java:94)
	at KWS.prepare.autoMan.getElement(autoMan.java:63)
	at KWS.prepare.autoMan.moveToElement(autoMan.java:154)
	at KWS.prepare.testdata.readExcel(testdata.java:173)
	at KWS.prepare.t15_03_14_07_45_11.couplesearch(t15_03_14_07_45_11.java:12)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.TestNG.privateMain(TestNG.java:1364)
	at org.testng.TestNG.main(TestNG.java:1333)
]]>
    </error>
  </testcase> <!-- couplesearch -->
  <testcase name="_194899TKRegistryCoupleSearchUGVR" time="104.086" classname="KWS.prepare.t15_03_14_07_45_11"/>
</testsuite> <!-- KWS.prepare.t15_03_14_07_45_11 -->
