<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="GZ-QA-AutoTool" name="KWS.prepare.t15_04_20_01_41_20" tests="1" failures="0" timestamp="20 Apr 2015 08:41:43 GMT" time="16.177" errors="1">
  <testcase name="UBVR_AddManualRegistry" time="16.177" classname="KWS.prepare.t15_04_20_01_41_20">
    <error type="java.lang.AssertionError" message="connect to DB failed, please check your account">
      <![CDATA[java.lang.AssertionError: connect to DB failed, please check your account
	at org.testng.Assert.fail(Assert.java:94)
	at KWS.prepare.autoMan.SqlsOperation(autoMan.java:218)
	at KWS.prepare.testdata.readExcel(testdata.java:113)
	at KWS.prepare.t15_04_20_01_41_20.UBVR_AddManualRegistry(t15_04_20_01_41_20.java:8)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.TestNG.privateMain(TestNG.java:1364)
	at org.testng.TestNG.main(TestNG.java:1333)
]]>
    </error>
  </testcase> <!-- UBVR_AddManualRegistry -->
</testsuite> <!-- KWS.prepare.t15_04_20_01_41_20 -->
